# Generated by Django 2.2 on 2019-05-12 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20190512_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
