language: python
dist: xenial
python:
- '3.7'
env:
- DJANGO=2.2 DB=sqlite
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: aIg77u76bn41RmxCZmKsC8SsKjMpUGumwkKLEuhNCW12697Gd7q5Z+3NZy6Awj4XuwHx29XZKOa7TjlyAj4GNxjaKEkFsDoPxkfp/Kw6d4QuSByLdfKGe3bM55MA5ghpm0lLw1/iJ2KU+cCYmrtFq+kki7gtSxzRpCUkBi/3XsqdQEMBeMtQ0Yp2Spwwa7gNpQGat5nyTAUGyne081RNzdmZyFxaQSgpq/ZfFf2r8fJRwdKoWb5PPn3lvWZdKGez9APY6HFXYkkF75o7AfGvIpC1Vl2vDivbRVKQwpOfUX0g1VkZjk3KfQExRo12nCoy18N2YmL5iEPHYKemSJTzN040Pr2tJnCCu5lDFg7wddx/1mGQgXpFApAf0W2IOWmzR5yUTJn+b9PbofDZBI12obB3oaRGR22WDsxvb2Dc+D+ka07kZtt1MqcY46fkaP9jDMZsnTHwrpHKsSVbqQ6XfcJdZVtvhdVtlOQyNopMdvSdAF6T+cRKK/iPD4B6892226jD0qi4J1tmEzytRJESJia7/jWD6F9wJspBqv3oiigSMzQ53jxHrnyx5Qh0ZqpTVqaWtuKzr8g6Q9BJLhHMihxN6BiFz4TWtqgiQGU2TBw99oUxuuob/kwureh6TacSflK7C1+AvwyKilnJ0ErApK3kC3XqlBWOxw+4JJhcMBw=
notifications:
  slack:
    on_failure: always
    on_success: always
    secure: ISGRsYvtKx+PusIM0GkB1LIAEdeIxrwHHV+CueMlACGII8YULVtGh3f8Ur3BkOYvexFrPkaYYpNWnyDIrKtFpdG74lrFqzRzeY7gn9puaephuquX91CJWAfbuL9OekAi7tMNCrYnN1dXOcsmF2T4fmphhpHO5PsiLAwrUvY5yDqvFPnv7LL5DxcybNsuS4K62MYDcRFln14Iqwv6u0feLfAgsjPjuv6yvS4fSlr0S8KdnUb+A4podUKfzuRJTnYjEnY+N4aXFQZiDzMi+5aJzq4goa9gSfUX2Kz80YsXGc3/hFihaEzopfM+j3zI6tEEyHNl0V7/XOLD/8xX05BdZIjm9RFX5FK0gNo/BVCHm7F3ny3MYpUj0Tcl9vXXSQLNip/9AFRWlMBAbG0jm01YRQCiqFepnJz0Zd+deow0IaxgCFA5sZ0G4+/d8O56GSYygPKHa/ID1NeKZVxJ7AKPdr9vAi0y4LwALIZteExqmT9FhCdLd3+Rly7iozIm9P7IiAwx9B7KPXFSbrOsTntZsXFY8VO3Js8h9bZgEv6BxPjn4ElyAJTaS/cgCRfWU+29PeT+Z792mbWCavci25X/+bP4X4AdOMo90itDGrd9CvNyHR7Q4+VCDs4+fhARBo1EPLQU9iYldPKX9OKagGEsdM9ORJ5v+4ToZ4bJIGL2n98=
