language: python
dist: xenial
python:
- '3.7'
env:
- DJANGO=2.2 DB=sqlite
install:
- pip install -r requirements.txt
script:
- python manage.py test
notifications:
  slack:
    secure: oXBWZ/zpzekiGuwywLFrRRViNct5a2rmoBL4Xgj54xKon1Tsw4h/YJmlsbNX8e2VLLCFuOFOA8RBrTbe4MzchQvc9sDJtIq2o7OARPnW98NQOo1GpYFlk/+S0iE42oRTgCmPcmP/AOHOLVeve+NjXuCc/UyiHX0lifHqEK8tq+kY+Nm/+vxth56IfvaVIh8UQm8nWcLgRd8dMGf9frgrJmcOuXRK4ymLk14M0xHQNE2odF6c+DoWCYvPsekhGmfuanUxVqlrrRiJuD5jDBPc9viTOyJJk+SSvM0VdV2zy0QCc4DrNSTUBt8ZkvfXIach3GWb0JJPB/TZi2u3AAQHJ5zjkfEuwUUYpHP/N4AUhQvisG8boSOzo8+iEvz3xNrMHxkjrEmizqN2V3XBGKHSUZjd65vraNRUKol84sKKzAa9YiW6D8WVnhw30Ywkeb040wWDSQSKx/wH8Lb8KL2jxxkSuoCCCAK1rlRkXKCFZ//qiEQ+k9hB2+dj6ZZcn/9zewzSn5RrcpoMcmY6G1ricwh2OIz4RDSgCMmH9841hu0SbK9at1/xyXkNfdRTfPkYUKBOfh2JabXQH+DxidOJfPblH4ptcG7QfA05H93RBewIcT/v8mTZPjpX0iuMazdgk7ejODgeop9fpYPH2rq6rN3GpHuTBYA8SUODUTKf03U=
