language: python
dist: xenial
python:
- '3.7'
env:
- DJANGO=2.2 DB=sqlite
install:
- pip install -r requirements.txt
script:
- python manage.py test
notifications:
  slack:
    secure: oXBWZ/zpzekiGuwywLFrRRViNct5a2rmoBL4Xgj54xKon1Tsw4h/YJmlsbNX8e2VLLCFuOFOA8RBrTbe4MzchQvc9sDJtIq2o7OARPnW98NQOo1GpYFlk/+S0iE42oRTgCmPcmP/AOHOLVeve+NjXuCc/UyiHX0lifHqEK8tq+kY+Nm/+vxth56IfvaVIh8UQm8nWcLgRd8dMGf9frgrJmcOuXRK4ymLk14M0xHQNE2odF6c+DoWCYvPsekhGmfuanUxVqlrrRiJuD5jDBPc9viTOyJJk+SSvM0VdV2zy0QCc4DrNSTUBt8ZkvfXIach3GWb0JJPB/TZi2u3AAQHJ5zjkfEuwUUYpHP/N4AUhQvisG8boSOzo8+iEvz3xNrMHxkjrEmizqN2V3XBGKHSUZjd65vraNRUKol84sKKzAa9YiW6D8WVnhw30Ywkeb040wWDSQSKx/wH8Lb8KL2jxxkSuoCCCAK1rlRkXKCFZ//qiEQ+k9hB2+dj6ZZcn/9zewzSn5RrcpoMcmY6G1ricwh2OIz4RDSgCMmH9841hu0SbK9at1/xyXkNfdRTfPkYUKBOfh2JabXQH+DxidOJfPblH4ptcG7QfA05H93RBewIcT/v8mTZPjpX0iuMazdgk7ejODgeop9fpYPH2rq6rN3GpHuTBYA8SUODUTKf03U=
deploy:
  provider: heroku
  api_key:
    secure: jlFQ2XeiRKW3tkSSNjEFa4vp3sVoj9/0QZfUDAgsW7OyZDL/qEAz4O1Xe5+DupM3uM271TKhtG9gjSl8D9aZu3jH2XC0Xc/Aw5/vF3BIaI2u5OahZqWX49UtC4qkUYW6tTeOLbHQK5AsIavcJOHN6LP8H97DcGi2jES6Fj7J30DHL0/y7B5cYKwFXta7lPp1+n4jxP3MlUXDm6rZsr+XbxzVhpsxnXiJjnTFeRuIB/aiyPxPZDMMs+D9u7DYNMKgh72LJFLUzrxWZrpHzWz1ZPP0IzvqndRMSkyy6HiQFwh4OI/djNWXOoRdz9Q8zpYV06iyg9xBKREjH/I5Ntq6cx4CRlSpo8QUHQOxHGJhaBjGHz97X6AW+gX84JCuFkok+UDlZBlljdwuPyH58o6j7UrHI98zW4a6ecJrYrbCVmEMY4fFKCHDw+YV3PGRCmc9AKbT6Ohu9139NZq4JVQpWK9w6oJu4fePRs+DS/hh4mv39bkrxpgjX+wcm8OZhxpx8tmr0w2NWexaetyZbXEnfQsZ3yCUv+mlOm52H4cjDUXVktyLCT4LCQVpIbYaPHZyE0e+6vrHR8N5JleAPkhUuEndlmJYFC2VzeucCZcVqQ2lQvqUneED5NRyXN/1S3k07mHUE5cUy4eE1ORLSBVnQ+NY5aI/ObwN0SESx+GvPWs=
  app: wishlist-dev-pzl
  on:
    repo: puzzle-team-v2-0/wishlist-server
  run:
  - "python wishlist_server/manage.py migrate"
  - restart
