language: python
dist: xenial
python:
  - "3.7"
env:
  - DJANGO=2.2 DB=sqlite
install:
 - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "aIg77u76bn41RmxCZmKsC8SsKjMpUGumwkKLEuhNCW12697Gd7q5Z+3NZy6Awj4XuwHx29XZKOa7TjlyAj4GNxjaKEkFsDoPxkfp/Kw6d4QuSByLdfKGe3bM55MA5ghpm0lLw1/iJ2KU+cCYmrtFq+kki7gtSxzRpCUkBi/3XsqdQEMBeMtQ0Yp2Spwwa7gNpQGat5nyTAUGyne081RNzdmZyFxaQSgpq/ZfFf2r8fJRwdKoWb5PPn3lvWZdKGez9APY6HFXYkkF75o7AfGvIpC1Vl2vDivbRVKQwpOfUX0g1VkZjk3KfQExRo12nCoy18N2YmL5iEPHYKemSJTzN040Pr2tJnCCu5lDFg7wddx/1mGQgXpFApAf0W2IOWmzR5yUTJn+b9PbofDZBI12obB3oaRGR22WDsxvb2Dc+D+ka07kZtt1MqcY46fkaP9jDMZsnTHwrpHKsSVbqQ6XfcJdZVtvhdVtlOQyNopMdvSdAF6T+cRKK/iPD4B6892226jD0qi4J1tmEzytRJESJia7/jWD6F9wJspBqv3oiigSMzQ53jxHrnyx5Qh0ZqpTVqaWtuKzr8g6Q9BJLhHMihxN6BiFz4TWtqgiQGU2TBw99oUxuuob/kwureh6TacSflK7C1+AvwyKilnJ0ErApK3kC3XqlBWOxw+4JJhcMBw="
